# article_mappings.py

def map_supplier():
    return [
        ("ABUS", 17280, "ABU"),
        ("DEMAG", 4975, "DEM"), # Supplier Van den berg
        ("HUCHEZ", 4355, "HUC"),
        ("VETTER", 4996, "VET"),
        ("IGUS", 4377, "IGU"),
        ("DANFOSS (IKUSI)", 4390, "DAN"),
        ("SEW", 4815, "SEW"),
        ("KARL GEORG", 4442, "KG"),
        ("OLSEN", 1, "OLS"),
        ("STEMM", 4892, "STE"),
        ("AGEMA", 3832, "AGE"),
        ("MANTION", 25086, "MAN"),
        ("MOBILIS", 4262, "MOB"), # Supplier Faraco
        ("ALIS-TECH", 30837, "ALI"),
        ("REMA", 27834, "REM"),
        ("FARACO", 4262, "FAR"),
    ]

def map_abbreviation():
    return [
        ("Pont roulant", "PR", True),
        ("Pont roulant monopoutre", "PR", True),
        ("Pont roulant bipoutre", "PR", True),
        ("Pont suspendu monopoutre", "PR", True),
        ("Poutre roulante", "PR", True),
        ("Portique", "PO", True),
        ("Portique léger", "PO", True),
        ("Potence sur fût", "PT", True),
        ("Potence murale", "PT", True),
        ("Potence murale WSK (KBK)", "PT", True),
        ("Potence sur fut SSK (KBK)", "PT", True),
        ("Système modulaire HB", "HB", True),
        ("Système modulaire KBK", "KBK", True),
        ("Palan à chaîne", "PA", True),
        ("Palan à câble", "PA", True),
        ("Palan à manuels", "PA", True),
        ("Palan électrique", "PA", True),
        ("Palan", "PA", True),
        ("Alimentation", "ALIM", False),
        ("Elite", "ALIM", False),
        ("Inno", "ALIM", False),
        ("Movit", "ALIM", False),
        ("Grue vélocipède", "GRU", False),
        ("Kit", "KIT", True),
        ("Divers", "DIV", False),
        ("Palonnier", "PAL", True),
        ("Monorail", "MONO", True),
        ("Grappin", "GRA", True),
        ("Pince", "PIN", True),
        ("Galet", "GAL", False),
        ("Bloc galet", "GAL", False),
        ("Galet équipe", "GAL", False),
        ("Système de galet", "GAL", False),
        ("Système de bloc galet", "GAL", False),
        ("Chemin de roulement", "CR", False),
        ("Structure", "STR", False),
        ("Potence", "PT", True),
        ("Chariot électrique", "CHA", False),
        ("Chariot libre", "CHA", False),
        ("Chariot manuel", "CHA", False),
        ("Chariot à commande électrique", "CHA", False),
        ("Chariot à translation libre", "CHA", False),
        ("Moteur", "MOT", False),
        ("Motoréducteur", "MOT", False),
        ("Moteur à rotor cylindrique", "MOT", False),
        ("Moteur-freins à rotor conique", "MOT", False),
        ("Motoréducteur à arbre parraelle", "MOT", False),
        ("Motoréducteur à acouple conique", "MOT", False),
        ("Motoréducteur à engrenage cylindrique", "MOT", False),
        ("Réducteur", "RED", False),
        ("Kit Radio", "KIT", False),
        ("Radio", "RAD", False),
        ("Treuil", "TR", True),
        ("Chassis", "STR", True),
        ("Ancrage", "STR", False),
        ("Mécanosoudé", "STR", True),
        ("Construction en acier standard HB", "STR", False),
        ("Appareillage", "APP", False),
        ("Transtockeur", "TRA", False),
        ("Projecteur LED de sécurité", "LED", False),
        ("Système de transmission", "Kit", False),
        ("Chaine à cable", "Alim", False),
        ("Chariot manuel translation à chaîne","CHA", False),
        ("Chariots réglables","CHA", False),
        ("Chariots électriques","CHA", False),
        ("Elingues câble acier systéme S","KIT", False),
        ("Elingues câble acier systéme T","KIT", False),
        ("Grues mobiles d'atelier","GRU", True),
        ("Palans manuels", "PA", True),
        ("Palans à levier", "PA", True),
        ("Palans électriques", "PA", True),
        ("Palonniers", "PAL", True),
        ("Pince à poutre", "PIN", True),
        ("Pinces de levage horizontal", "PIN", True),
        ("Pinces de levage vertical", "PIN", True),
        ("Pince à fûts", "PIN", True),
        ("Portique en ALU réglable", "POR", True),
        ("Portique en acier fixe", "POR", True),
        ("Poulies", "POU", True),
        ("REMA INOX composants","KIT", False),
        ("REMA-10 composants différents","KIT", False),
        ("REMA-10 élingues chaîne complètes","KIT", False),
        ("Treuils manuels","TR", True),
        ("Treuils à câble passant","TR", True),
        ("Treuils à vis sans fin/à engrenages","TR", True),
        ("Treuils électriques","TR", True),
        ("Trépieds en aluminium","TRE", False),
        
        ("Guirlande complète","ALIM",False),
        ("Alimentation spécifique","ALIM",False),
        ("Enrouleur","ALIM",False),
        
    ]



def map_abus_product_discount():
    return {
        "Palan à câble": (30, 10),
        "Palan à chaîne": (35, 10),
        "Potence": (30, 10),
        "Système modulaire HB": (20, 10),
        "Portique léger": (30, 10),
        "Kit": (30, 10),
        "Chariot manuel": (35, 0),
        "Chariot électrique": (35, 0),
        "Alimentation": (30, 0),
        "Grue vélocipède": (30, 10),
    }
def map_abus_type_discount():
    return {
        "DLVM": (34, 10),
        "EDK": (31, 10),
        "EDL": (34, 10),
        "EHPK": (31, 10),
        "ELK": (31, 10),
        "ELS": (31, 10),
        "ELV": (34, 10),
        "ZLK": (29, 10),
        "ZLV": (34, 10),
        "GMC": (35,  0),
    }
    
    
def map_abus_product_margin():
    return {
        "Palan à câble": 30,
        "Palan à chaîne": 30,
        "Potence": 25,
        "Système modulaire HB": 25,
        "Portique léger": 25,
        "Kit": 20,
        "Chariot manuel": 30,
        "Chariot électrique": 30,
        "Alimentation": 30,
        "Grue vélocipède": 20,
        "Pont roulant": 20,
    }

def map_exclude_words():
    return [
        "Pièce individuelle",
        "Pièces détchées compétiteurs",
        "Pièces individuelles d'alim.",
        "Pièces individuelles guirlande d'alim.",
        "Pièces détachées",
        "Buttoir (sommier)",
        "Buttoir (à clamer)",
        "Buttoirs",
        "Câble de levage",
        "Chaine d'énergie complète",
        "Câbles",
        "poignée pendante",
        "Matériel d'installation électrique",
        "composants, universels",
        "convoyeur aérien (grues + pièces détachées)",
        "Contacteurs",
        "PRODUITS",
        "Accesoires",
        "BEL",
        "LUX",
        "mini coussin",
        "Fixations",
        
        "Accessoires pour câbles de suspension",
        "Accessoires pour câbles plats",
        "Accessoires pour transpalette",
        "Aimants de levage à batterie",
        "Aimants à main compacts",
        "Amortisseurs à largeur réglables",
        "Anneaux de levage (G10)",
        "Bras téléscopique",
        "Capteur mecanique sur cable",
        "Chariots à fûts",
        "Chaînes",
        "Commandes à distance sans fil (radio)",
        "Cric à crémaillère",
        "Crics hydrauliques (lève-machines)",
        "Crics à fût montant DMK",
        "Crics à fût montant VHS et KBH",
        "Crochet à sangle avec linguet",
        "Crochets G8",
        "Dynamomètre DSD04",
        "Dynamomètre DSD05",
        "Dynamomètre mécanique REMA type TEO",
        "Elingues sangles rondes",
        "Fourches palettes",
        "Levage et manutention des éléments en béton",
        "Manilles de levage",
        "Moufle à câble",
        "Oeillet de levage C15",
        "Oeillet de levage et crochet à souder (G8)",
        "PFR aimant de levage",
        "Patins rouleurs",
        "Pince à fûts REMA type DG10",
        "Pinces pour levage des blocs et tuyaux",
        "Pinces pour levage des poutres",
        "Pinces pour levage des profiles",
        "Pinces pour levage des rails",
        "Pinces pour traction des palettes",
        "Pinces à visser",
        "Protection coin",
        "Protection pour sangles",
        "QPM aimant de levage",
        "Rema-All",
        "Sangles d'arrimage",
        "Sangles plate en polyester (PES)",
        "Sangles plates en PES avec triangles",
        "Sangles tubulaires sans fin en polyester (PES)",
        "Table élévatrice fixe à double ciseaux, électrique",
        "Table élévatrice fixe, modèle basse, forme “U”, électrique",
        "Table élévatrice fixe, modèle basse, électrique",
        "Table élévatrice fixe, électrique",
        "Tables élévatrices mobiles: manuelles",
        "Tendeurs d' arrimage G8-G10",
        "Transpalette versions spéciales",
        "Transpalettes",
        "Transpalettes hauteur élevée",
        "Treuils de traction/levage 230/400VAC",
        "Ventouses de levage mécanique",
    ]

def _get_key():
    return b'4wZvCl7drUs0ROIOaYwz1mYsDPVXuU-YiqwqnOYL07Q='